##########
### EN ###
##########

# Menu
current_language = "Current language:"
download_directory = "Download directory:"

menu_title = "<b>===== <red>YouTube Downloader</red> =====</b>"
menu_add_url = "1. Add URL to download queue"
menu_list_queue = "2. List queued downloads"
menu_start_downloads = "3. Start downloads"
menu_view_history = "4. View download history"
menu_clear_queue = "5. Clear download queue"
menu_settings = "6. Settings"
menu_exit = "7. Exit"
menu_enter_choice = "Enter choice (1-7): <b><blue>"

# Settings menu
settings_title = "Settings:"
settings_language = "1. Change language"
settings_set_directory = "2. Set download directory"
settings_coloring = "3. Enable/disable coloring"
settings_back = "4. Back to main menu"
settings_enter_choice = "Enter choice (1-4): <b><blue>"

# Language selection
language_select = "Select a language:"
language_english = "English"
language_hungarian = "Magyar"
language_back = "Back to main menu"
language_enter_choice = "Enter choice ({}-{}): <b><blue>"
language_set_english = "<green>Language set to English.</green>"

# Messages
download_queue_empty = "<red>Download queue is empty</red>"
download_queue_title = "--- Download Queue ---"
no_urls_to_download = "<bright_red>No URLs in queue to download.</bright_red>"
starting_download = "<green>Starting download for {} music's...</green>"
video_downloading = "Downloading: {}"
video_downloaded = "✓ Downloaded {} in {}'s"
video_download_failed = "✗ Error downloading {}: {}"
download_summary = "<b><blue>Download summary:</blue></b>"
download_success = "<green>Successfully downloaded</green>: <green>{}</green>/{}"
download_fail = "<yellow>- Failed downloads: {}</yellow>"
dir_set = "Download directory set to: {}"
no_dir_selected = "<bright_red>No directory selected.</bright_red>"
no_history = "No download history available."
history_title = "--- Download History ---"
history_more = "...and {} more"
queue_cleared = "Cleared {} items from the download queue"
exiting = "<bright_magenta>Exiting...</bright_magenta>"
app_stopped = "<bright_cyan>Application stopped.</bright_cyan>"
invalid_choice = "<red>Invalid choice. Please enter a number between {} and {}.</red>"
return_to_menu = "Returning to main menu..."
enter_url = "Enter YouTube URL: <b><blue>"
fetching_info = "Fetching music information..."
fetching_video_info = "Fetching info for: {}"
added_to_queue = "<green>Added to queue</green>: {}"
already_added = "<yellow>This music already in the list!</yellow>"
error_fetching = "<bright_red>Error fetching music info: {}</bright_red>" 