##########
### HU ###
##########

# Menu
current_language = "Jelenlegi nyelv:"
download_directory = "Jelenlegi letöltési mappa:"

menu_title = "<b>===== <red>DownTone Letöltő</red> =====</b>"
menu_add_url = "1. URL hozzáadása a letöltési listához"
menu_list_queue = "2. Letöltési lista megjelenítése"
menu_start_downloads = "3. Letöltés indítása"
menu_view_history = "4. Letöltési előzmények"
menu_clear_queue = "5. Letöltési lista kiűrítés"
menu_settings = "6. Beállítások"
menu_exit = "7. Kilépés"
menu_enter_choice = "Válassz egy opciót (1-7): <b><blue>"

# Settings menu
settings_title = "Beállítások:"
settings_language = "1. Nyelv módosítása"
settings_set_directory = "2. Letöltési mappa beállítása"
settings_coloring = "3. Színek bekapcsolása/kikapcsolása"
settings_back = "4. Vissza a főmenübe"
settings_enter_choice = "Válassz egy opciót (1-4): <b><blue>"

# Language selection
language_select = "Válassz nyelvet:"
language_english = "English"
language_hungarian = "Magyar"
language_back = "Vissza a főmenübe"
language_enter_choice = "Válassz egy opciót ({}-{}): <b><blue>"
language_set_hungarian = "<green>A nyelv magyarra lett állítva.</green>"

# Messages
download_queue_empty = "<red>A letöltési lista üres</red>"
download_queue_title = "--- Letöltési Lista ---"
no_urls_to_download = "<bright_red>Nincsenek URL-ek a letöltési listában.</bright_red>"
starting_download = "<green>{} videó letöltésének indítása...</green>"
video_downloading = "<yellow>↓</yellow> Letöltés: {}"
video_downloaded = "<green>✓</green> {} | ⏰: {}mp"
video_download_failed = "<bright_red>✗</bright_red> Sikertelen letöltés {}: {}"
download_summary = "<b><blue>Letöltési összegzés:</blue></b>"
download_success = "Sikeresen letöltve: <green>{}</green>/{}"
download_fail = "Sikertelen letöltések: <bright_red>{}</bright_red>"
dir_set = "Letöltési mappa beállítva: {}"
no_dir_selected = "<bright_red>Nem választottál mappát.</bright_red>"
no_history = "Nincs elérhető letöltési előzmény."
history_title = "--- Letöltési Előzmények ---"
history_more = "...és még {} több"
queue_cleared = "{} elem törölve a letöltési listából"
exiting = "<bright_magenta>Kilépés...</bright_magenta>"
app_stopped = "<bright_cyan>Az alkalmazás leállt.</bright_cyan>"
invalid_choice = "<red>Érvénytelen választás. Kérlek, adj meg egy számot {} és {} között.</red>"
return_to_menu = "Visszatérés a főmenübe..."
enter_url = "Add meg a YouTube URL-t: <b><blue>"
fetching_info = "Link információi lekérése..."
fetching_video_info = "Videó adatai lekérdezése: {}"
added_to_queue = "<green>Hozzáadva a listához</green>: {}"
already_added = "<yellow>Ez a zene már bennevan a listában!</yellow>"
error_fetching = "<bright_red>Hiba a videó információk lekérésekor: {}</bright_red>"